DistManagment/Controllers/agentOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistManagment.Controllers
{
    public class agentOrderController : Controller
    {
        private DistManEntities db = new DistManEntities();

        //
        // GET: /agentOrder/

        public ActionResult Index()
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            var order_agent = db.order_agent.Include(o => o.order).Include(o => o.user);
            return View(order_agent.ToList());
        }

        //
        // GET: /agentOrder/Details/5

        public ActionResult Details(int id = 0)
        {
            order_agent order_agent = db.order_agent.Find(id);
            if (order_agent == null)
            {
                return HttpNotFound();
            }
            return View(order_agent);
        }

        //
        // GET: /agentOrder/Create

        public ActionResult Create()
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            ViewBag.order_id = new SelectList(db.order, "id", "order_name");
            ViewBag.user_id = new SelectList(db.users, "id", "username");
            return View();
        }

        //
        // POST: /agentOrder/Create

        [HttpPost]
        public ActionResult Create(order_agent order_agent)
        {
            if (ModelState.IsValid)
            {
                db.order_agent.Add(order_agent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.order_id = new SelectList(db.order, "id", "order_name", order_agent.order_id);
            ViewBag.user_id = new SelectList(db.users, "id", "username", order_agent.user_id);
            return View(order_agent);
        }

        //
        // GET: /agentOrder/Edit/5

        public ActionResult Edit(int id = 0)
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order_agent order_agent = db.order_agent.Find(id);
            if (order_agent == null)
            {
                return HttpNotFound();
            }
            ViewBag.order_id = new SelectList(db.order, "id", "order_name", order_agent.order_id);
            ViewBag.user_id = new SelectList(db.users, "id", "username", order_agent.user_id);
            return View(order_agent);
        }

        //
        // POST: /agentOrder/Edit/5

        [HttpPost]
        public ActionResult Edit(order_agent order_agent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order_agent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.order_id = new SelectList(db.order, "id", "order_name", order_agent.order_id);
            ViewBag.user_id = new SelectList(db.users, "id", "username", order_agent.user_id);
            return View(order_agent);
        }

        //
        // GET: /agentOrder/Delete/5

        public ActionResult Delete(int id = 0)
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order_agent order_agent = db.order_agent.Find(id);
            if (order_agent == null)
            {
                return HttpNotFound();
            }
            return View(order_agent);
        }

        //
        // POST: /agentOrder/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            order_agent order_agent = db.order_agent.Find(id);
            db.order_agent.Remove(order_agent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DistManagment/Controllers/orderProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistManagment.Controllers
{
    public class orderProductsController : Controller
    {
        private DistManEntities db = new DistManEntities();

        //
        // GET: /orderProducts/

        public ActionResult Index()
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            var order_product = db.order_product.Include(o => o.order).Include(o => o.product);
            return View(order_product.ToList());
        }

        //
        // GET: /orderProducts/Details/5

        public ActionResult Details(int id = 0)
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order_product order_product = db.order_product.Find(id);
            if (order_product == null)
            {
                return HttpNotFound();
            }
            return View(order_product);
        }

        //
        // GET: /orderProducts/Create

        public ActionResult Create()
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            ViewBag.order_id = new SelectList(db.order, "id", "order_name");
            ViewBag.product_id = new SelectList(db.products, "id", "product_name");
            return View();
        }

        //
        // POST: /orderProducts/Create

        [HttpPost]
        public ActionResult Create(order_product order_product)
        {
            ViewBag.order_id = new SelectList(db.order, "id", "order_name", order_product.order_id);
            ViewBag.product_id = new SelectList(db.products, "id", "product_name", order_product.product_id);
            int tempId = order_product.product_id;
            products product = db.products.Find(tempId);
            if (order_product.qty > product.stock)
            {
                ViewBag.error = "Stock Not available";
                return View(order_product);
            }
            product.stock = product.stock - order_product.qty;

            if (ModelState.IsValid)
            {
                db.order_product.Add(order_product);
                db.SaveChanges();
                saveProduct(product);
                return RedirectToAction("Index");
            }

            
            return View(order_product);
        }

        //
        // GET: /orderProducts/Edit/5

        public ActionResult Edit(int id = 0)
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order_product order_product = db.order_product.Find(id);
            if (order_product == null)
            {
                return HttpNotFound();
            }
            ViewBag.order_id = new SelectList(db.order, "id", "order_name", order_product.order_id);
            ViewBag.product_id = new SelectList(db.products, "id", "product_name", order_product.product_id);
       
            return View(order_product);
        }

        //
        // POST: /orderProducts/Edit/5

        [HttpPost]
        public ActionResult Edit(order_product order_product)
        {
            ViewBag.order_id = new SelectList(db.order, "id", "order_name", order_product.order_id);
            ViewBag.product_id = new SelectList(db.products, "id", "product_name", order_product.product_id);
            int tempId = order_product.product_id;
            products product = db.products.Find(tempId);
            if (order_product.qty > product.stock)
            {
                ViewBag.error = "Stock Not available";
                return View(order_product);
            }
            product.stock = product.stock - order_product.qty;

            if (ModelState.IsValid)
            {
                db.Entry(order_product).State = EntityState.Modified;
                db.SaveChanges();
                saveProduct(product);
                return RedirectToAction("Index");
            }
           
            return View(order_product);
        }
        public void saveProduct(products p1){
            db.Entry(p1).State = EntityState.Modified;
            db.SaveChanges();
        }
        //
        // GET: /orderProducts/Delete/5

        public ActionResult Delete(int id = 0)
        {

            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order_product order_product = db.order_product.Find(id);
            if (order_product == null)
            {
                return HttpNotFound();
            }
            return View(order_product);
        }

        //
        // POST: /orderProducts/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            order_product order_product = db.order_product.Find(id);
            db.order_product.Remove(order_product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DistManagment/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistManagment.Controllers
{
    public class ordersController : Controller
    {
        private DistManEntities db = new DistManEntities();

        //
        // GET: /orders/

        public ActionResult Index()
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }
            catch (Exception et) { return RedirectToAction("LoginUser", "Home"); }
          
            return View(db.order.ToList());
        }

        //
        // GET: /orders/Details/5

        public ActionResult Details(int id = 0)
        {
            try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }
            catch (Exception et) { return RedirectToAction("LoginUser", "Home"); }
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // GET: /orders/Create

        public ActionResult Create()
        {
             try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            return View();
        }

        //
        // POST: /orders/Create

        [HttpPost]
        public ActionResult Create(order order)
        {
            if (ModelState.IsValid)
            {
                db.order.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        //
        // GET: /orders/Edit/5

        public ActionResult Edit(int id = 0)
        {
             try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /orders/Edit/5

        [HttpPost]
        public ActionResult Edit(order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        //
        // GET: /orders/Delete/5

        public ActionResult Delete(int id = 0)
        {
             try { if (Session["userid"].ToString() == "") { return RedirectToAction("LoginUser", "Home"); } }catch (Exception et) {return RedirectToAction("LoginUser", "Home"); }
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /orders/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            order order = db.order.Find(id);
            db.order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DistManagment/Views/orders/Create.cshtml
@model DistManagment.order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>order</legend>

        <div class="editor-label">
            Order Name
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.order_name)
            @Html.ValidationMessageFor(model => model.order_name)
        </div>

        <div class="editor-label">
           Order Delivered  To
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.deliver_to)
            @Html.ValidationMessageFor(model => model.deliver_to)
        </div>

        <div class="editor-label">
            Delivery Date
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.deliver_date)
            @Html.ValidationMessageFor(model => model.deliver_date)
        </div>

        <div class="editor-label">
            Quantity
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.qty)
            @Html.ValidationMessageFor(model => model.qty)
        </div>

        <div class="editor-label">
            Delivered ?
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.status)
            @Html.ValidationMessageFor(model => model.status)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DistManagment/Views/orders/Delete.cshtml
@model DistManagment.order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>order</legend>

    <div class="display-label">
        Order Name
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.order_name)
    </div>

    <div class="display-label">
         Order Delivered  To
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.deliver_to)
    </div>

    <div class="display-label">
         Delivery Date
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.deliver_date)
    </div>

    <div class="display-label">
         Quantity
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.qty)
    </div>
    <div class="display-label">
        Status
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.status)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

DistManagment/Views/orders/Details.cshtml
@model DistManagment.order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>order</legend>

   <div class="display-label">
        Order Name
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.order_name)
    </div>

    <div class="display-label">
         Order Delivered  To
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.deliver_to)
    </div>

    <div class="display-label">
         Delivery Date
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.deliver_date)
    </div>

    <div class="display-label">
         Quantity
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.qty)
    </div>

    <div class="display-label">
        Status
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.status)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DistManagment/Views/orders/Edit.cshtml
@model DistManagment.order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>order</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
           Order Name
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.order_name)
            @Html.ValidationMessageFor(model => model.order_name)
        </div>

        <div class="editor-label">
          Order Delivered  To
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.deliver_to)
            @Html.ValidationMessageFor(model => model.deliver_to)
        </div>

        <div class="editor-label">
           Delivery Date
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.deliver_date)
            @Html.ValidationMessageFor(model => model.deliver_date)
        </div>

        <div class="editor-label">
            Quantity
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.qty)
            @Html.ValidationMessageFor(model => model.qty)
        </div>

        <div class="editor-label">
            Delivered
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.status)
            @Html.ValidationMessageFor(model => model.status)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DistManagment/Views/orders/Index.cshtml
@model IEnumerable<DistManagment.order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th style="width:10%;">Order Name
        </th>
        <th style="width:25%;">Order Delivered  To
        </th>
        <th style="width:10%;">Delivery Date
        </th>
        <th style="width:5%;" >Quantity
        </th>
        <th style="width:5%;">Delivered ?
        </th>
        <th style="width:20%;"></th>
        <th style="width:20%;"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.order_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.deliver_to)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.deliver_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @if(item.status==false){
                @Html.ActionLink("Assign to Agent", "Create", "agentOrder") 
                 @Html.ActionLink("Add Product to Order", "Create", "orderProducts")
                 }
            </td>
            <td>

                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>